import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Alexandria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col bg-cyan-400 min-h-screen items-center  ">
        <h1 className="font-bold text-3xl">📜 Alexandria . . .</h1>

        <div className="animate-bounce  text-2xl m-4 font-light">Content</div>
      </div>
    </>
  );
}
